### PR TITLE
Replace RMySQL with RMariaDB

### PR DESCRIPTION
**Pull request by martin-g**
As per https://github.com/r-dbi/RMySQL#rmysql: 
```
NOTE: this package is being phased out in favor of the new RMariaDB package.
```

Bump the version to 1.12.0

### CODE REVIEW

**Comment by martin-g** [comment]
Any feedback on the proposed change ?

**Comment by julien-faye** [comment]
I am not a member of the team and far from expert in GladiaTOX but the idea to move away from the non-maintained RMySQL to RMariaDB sounds very good to me!
I've tested the PR locally and the build and check passed! :+1:

**Comment by martin-g** [comment]
Thank you for the feedback, @julien-faye !

Here is the output for `R CMD build` and `R CMD check` on my machine:
```
$ R CMD build GladiaTOX
* checking for file ‘GladiaTOX/DESCRIPTION’ ... OK
* preparing ‘GladiaTOX’:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
Omitted ‘LazyData’ from DESCRIPTION
* building ‘GladiaTOX_1.12.0.tar.gz’
```

```
$ R CMD check GladiaTOX_1.12.0.tar.gz 
* using log directory ‘/home/biocbuild/git/GladiaTOX.Rcheck’
* using R version 4.3.1 (2023-06-16)
* using platform: aarch64-unknown-linux-gnu (64-bit)
* R was compiled by
    gcc (GCC) 10.3.1
    GNU Fortran (GCC) 10.3.1
* running under: openEuler 22.03 (LTS-SP1)
* using session charset: UTF-8
* checking for file ‘GladiaTOX/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘GladiaTOX’ version ‘1.12.0’
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘GladiaTOX’ can be installed ... OK
* checking installed package size ... NOTE
  installed size is  8.1Mb
  sub-directories of 1Mb or more:
    doc   2.8Mb
    sql   3.8Mb
* checking package directory ... OK
* checking ‘build’ directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking startup messages can be suppressed ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... NOTE
glCheckInput: no visible global function definition for ‘read.csv’
glLoadInput: no visible global function definition for ‘read.csv’
glPlotPosCtrlMEC: no visible binding for global variable ‘aenm_wrap’
glPlotPosCtrlMEC: no visible binding for global variable ‘modl_acc’
Undefined global functions or variables:
  aenm_wrap modl_acc read.csv
Consider adding
  importFrom("utils", "read.csv")
to your NAMESPACE file.
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking installed files from ‘inst/doc’ ... OK
* checking files in ‘vignettes’ ... OK
* checking examples ...
 OK
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘testthat.R’
 OK
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in ‘inst/doc’ ... OK
* checking running R code from vignettes ...
  ‘GladiaTOX.Rmd’ using ‘UTF-8’... OK
 NONE
* checking re-building of vignette outputs ... OK
* checking PDF version of manual ... OK
* DONE

Status: 2 NOTEs
See
  ‘/home/biocbuild/git/GladiaTOX.Rcheck/00check.log’
for details.
```

**Review by sgubianpm — APPROVED** [review]

**Comment by sgubianpm** [comment]
@martin-g @julien-faye : LGTM. Merged. Thanks a lot for the PR. It makes totally sense, especially with RMySQL not being maintained.
@scanopm @fbonjourpmi : F.Y.I.

**Comment by martin-g** [comment]
Thank you for the merge, @sgubianpm !
Could you also please push it to Bioconductor (https://code.bioconductor.org/browse/GladiaTOX/commits/devel) ?

**Pull request merged**
